// <auto-generated />
using System;
using MentorHub.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MentorHub.API.Migrations
{
    [DbContext(typeof(MentorHubDbContext))]
    partial class MentorHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MentorHub.API.Models.Accounts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Expired")
                        .HasColumnType("datetime2")
                        .HasColumnName("eppired");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit")
                        .HasColumnName("is_used");

                    b.Property<long?>("Otp")
                        .HasColumnType("bigint")
                        .HasColumnName("otp");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("password");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("tbl_accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsUsed = false,
                            Password = "Pa$$word123",
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsUsed = false,
                            Password = "Pa$$word123",
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Username = "mentor"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsUsed = false,
                            Password = "Pa$$word123",
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Username = "mentee"
                        });
                });

            modelBuilder.Entity("MentorHub.API.Models.Employees", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("bio");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Experience")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("experience");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("last_name");

                    b.Property<Guid?>("MentorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("mentor_id");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("position");

                    b.HasKey("Id");

                    b.HasIndex("MentorId");

                    b.ToTable("tbl_employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Bio = "System Administrator.",
                            Email = "admin@hub.com",
                            Experience = "Senior",
                            FirstName = "Super",
                            LastName = "Admin",
                            Position = "System Analyst"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Bio = "Full-stack developer with 5 years experience.",
                            Email = "budi@hub.com",
                            Experience = "Expert",
                            FirstName = "Budi",
                            LastName = "Prasetyo",
                            Position = "Tech Lead"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Bio = "Junior developer learning C#.",
                            Email = "siti@hub.com",
                            Experience = "Junior",
                            FirstName = "Siti",
                            LastName = "Aisyah",
                            MentorId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Position = "Developer"
                        });
                });

            modelBuilder.Entity("MentorHub.API.Models.LearningGoals", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("datetime")
                        .HasColumnName("target_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("tbl_learning_goals", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Description = "Mampu mengimplementasikan CRUD dengan Entity Framework Core di ASP.NET.",
                            Status = "InProgress",
                            TargetDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Menguasai EF Core"
                        });
                });

            modelBuilder.Entity("MentorHub.API.Models.MenteeGoals", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LearningGoalsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LearningId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("learning_id");

                    b.Property<Guid>("MenteeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("mentee_id");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountsId");

                    b.HasIndex("LearningGoalsId");

                    b.HasIndex("LearningId");

                    b.HasIndex("MenteeId");

                    b.ToTable("tbl_mentee_goals", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cec21414-9509-4898-9587-ef8306781d7b"),
                            LearningId = new Guid("10000000-0000-0000-0000-000000000010"),
                            MenteeId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Status = 1
                        });
                });

            modelBuilder.Entity("MentorHub.API.Models.MentorSkills", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("mentor_id");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("skill_id");

                    b.Property<Guid?>("SkillsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountsId");

                    b.HasIndex("MentorId");

                    b.HasIndex("SkillId");

                    b.HasIndex("SkillsId");

                    b.ToTable("tbl_mentor_skills", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ee74eb17-ada5-4fc3-8604-48768fb97765"),
                            Level = 2,
                            MentorId = new Guid("10000000-0000-0000-0000-000000000002"),
                            SkillId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("fc94bbef-b663-421b-9343-0c7744233826"),
                            Level = 1,
                            MentorId = new Guid("10000000-0000-0000-0000-000000000002"),
                            SkillId = new Guid("10000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("MentorHub.API.Models.Roles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("tbl_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Mentor"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "Mentee"
                        });
                });

            modelBuilder.Entity("MentorHub.API.Models.Skills", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("tbl_skills", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Programming language for backend development.",
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Description = "Frontend and full-stack language.",
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Description = "Database query and management skill.",
                            Name = "SQL"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Description = "User experience and interface design.",
                            Name = "UX/UI Design"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Description = "Scripting and data analysis language.",
                            Name = "Python"
                        });
                });

            modelBuilder.Entity("MentorHub.API.Models.Accounts", b =>
                {
                    b.HasOne("MentorHub.API.Models.Roles", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MentorHub.API.Models.Employees", b =>
                {
                    b.HasOne("MentorHub.API.Models.Accounts", "Account")
                        .WithOne("Employee")
                        .HasForeignKey("MentorHub.API.Models.Employees", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MentorHub.API.Models.Employees", "Mentor")
                        .WithMany("Employee")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("MentorHub.API.Models.MenteeGoals", b =>
                {
                    b.HasOne("MentorHub.API.Models.Accounts", "Accounts")
                        .WithMany()
                        .HasForeignKey("AccountsId");

                    b.HasOne("MentorHub.API.Models.LearningGoals", "LearningGoals")
                        .WithMany()
                        .HasForeignKey("LearningGoalsId");

                    b.HasOne("MentorHub.API.Models.LearningGoals", null)
                        .WithMany("MenteeGoals")
                        .HasForeignKey("LearningId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MentorHub.API.Models.Accounts", null)
                        .WithMany("MenteeGoals")
                        .HasForeignKey("MenteeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("LearningGoals");
                });

            modelBuilder.Entity("MentorHub.API.Models.MentorSkills", b =>
                {
                    b.HasOne("MentorHub.API.Models.Accounts", "Accounts")
                        .WithMany()
                        .HasForeignKey("AccountsId");

                    b.HasOne("MentorHub.API.Models.Accounts", null)
                        .WithMany("MentorSkills")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MentorHub.API.Models.Skills", null)
                        .WithMany("MentorSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MentorHub.API.Models.Skills", "Skills")
                        .WithMany()
                        .HasForeignKey("SkillsId");

                    b.Navigation("Accounts");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("MentorHub.API.Models.Accounts", b =>
                {
                    b.Navigation("Employee");

                    b.Navigation("MenteeGoals");

                    b.Navigation("MentorSkills");
                });

            modelBuilder.Entity("MentorHub.API.Models.Employees", b =>
                {
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("MentorHub.API.Models.LearningGoals", b =>
                {
                    b.Navigation("MenteeGoals");
                });

            modelBuilder.Entity("MentorHub.API.Models.Roles", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("MentorHub.API.Models.Skills", b =>
                {
                    b.Navigation("MentorSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
